### PR TITLE
picasso: fix fstab

### PR DESCRIPTION
**Pull request by jjhitel**
This will fix the issues with logical partitions.

`
[libfs_mgr]Unmapped logical partition product
DM_DEV_REMOVE failed for [vendor]: Device or resource busy
Cannot unmap vendor before removing group qti_dynamic_partitions.
script aborted: assert failed: update_dynamic_partitions(package_extract_file("dynamic_partitions_op_list"))
assert failed: update_dynamic_partitions(package_extract_file("dynamic_partitions_op_list"))error: 25
Updater process ended with ERROR: 7
An assert failed. Please check the output above for more details.`

### CODE REVIEW

**Comment by masemoel** [comment]
Hi @jjhitel and thanks for your time in improving this repo.
Your issue looks like you are trying to flash a ZIP (either ROM or whatever else) with /system and /vendor partitions mounted (they come mounted by default, check them and untick them in **Mount** section, I need to find the way to solve this and make them coming unmounted by default).
Then your flashing issue should be gone (I know this as I had your issue as well while testing the recovery).

**Comment by jjhitel** [comment]
> Hi @jjhitel and thanks for your time in improving this repo.
> Your issue looks like you are trying to flash a ZIP (either ROM or whatever else) with /system and /vendor partitions mounted (they come mounted by default, check them and untick them in **Mount** section, I need to find the way to solve this and make them coming unmounted by default).
> Then your flashing issue should be gone (I know this as I had your issue as well while testing the recovery).

Yes, I know. But this commit allows flashing regardless of whether the partitions is mounted or not.

**Comment by masemoel** [comment]
After building both PBRP and TWRP with your fstab changes I am not able to mount system and vendor partitions, so I won't merge your pull request.
For me dynamic partitions were and are working fine actually. Remember always to **unmount system and vendor** after booting the recovery to avoid any flashing issue.

**Comment by jjhitel** [comment]
Oh, sorry... I just realized that I had a wrong understanding of SAR. So sorry to bother you...

**Comment by jjhitel** [comment]
@masemoel Okay, fixed the issue in the recovery source.

https://github.com/jjhitel/android_bootable_recovery/commits/sar-fix 
https://mega.nz/file/145QnLwS#ISrbUhk8275TRkNHmsA2YNDquzSpfTiHuzrJxyisB7M

**Comment by masemoel** [comment]
@jjhitel I have flashed your PBRP and saw it still boots with system and vendor pre-mounted.
Your commits looks like they automatically unmount before flashing any ZIP file, so the main part is...:
Can you tell me if you have tried that and worked? (I am sorry but I don't have enough time to flash a ROM, format data,etc... right now).

**Comment by jjhitel** [comment]
@masemoel Sorry, I should have told you that. Yes, it does work. I have tested with xiaomi.eu_multi_HMK305G_20.9.10_v12-11.zip.

Screenshot_PBRP_2020-09-25-01-14-33
[recovery_xiaomi.eu_multi_HMK305G_20.9.10_v12-11.zip_2020-09-25-01-13-26.log](https://github.com/masemoel/device_xiaomi_picasso_recovery_deprecated/files/5277183/recovery_xiaomi.eu_multi_HMK305G_20.9.10_v12-11.zip_2020-09-25-01-13-26.log)

**Comment by masemoel** [comment]
@jjhitel Perfect!!! I guess that, after flashing that zip and upgrading to Android 11, you won't be able to decrypt anymore (yeah, I have to look deeper into that while the A11's recovery source is being released).
Have you considered making a pull request to PitchBlack's original repo? So that it will fix this issue that affects all devices, afaik.
Anyway, thanks a lot for your contribution! I will build with your fork in the meanwhile :)

**Comment by jjhitel** [comment]
@masemoel 

Yes, I'm going to make a pull request.

And actually I have been using Android 11 since its first weekly build, and can decrypt in PBRP without any problems :)

**Comment by jjhitel** [comment]
@masemoel Yes, I'm going to make a pull request to PBRP's repo.
And I just downgraded to Android 10 and upgraded to Android 11 without wiping. Data decryption works in PBRP, but not in TWRP.

**Pull request closed without merging**
